### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException

### ISSUE THREAD

**Issue by rnemeth1980** [saucelabs-sample-test-frameworks/Groovy-Geb-Spock-Gradle-Selenium#4]
hi john,

I get exceptions while running the framework tests on windows 8.1. I have a sauce account, sauce connect is started and I may start tests.

**gradlew  sauceTest**
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:sauceTest

functionaltest.specs.StepwiseSpec > Search "hello!" FAILED
    org.openqa.selenium.UnsupportedCommandException

functionaltest.specs.BingSpec > Search "hello!" FAILED
    org.openqa.selenium.UnsupportedCommandException
    geb.driver.DriverCreationException
        Caused by: geb.driver.DriverCreationException

functionaltest.specs.StepwiseSpec > Search blank FAILED
    org.openqa.selenium.UnsupportedCommandException

functionaltest.specs.StepwiseSpec > classMethod FAILED
    geb.driver.DriverCreationException at StepwiseSpec.groovy:18
        Caused by: geb.driver.DriverCreationException at StepwiseSpec.groovy:18

any idea whats missing or what could be wrong?

thank you very much

**Comment by johnroach** [comment]
Interesting... Didn't get this one before. Checking it as soon as possible...

**Comment by johnroach** [comment]
Just to make sure, did you set your environment variables before running the tests? 
Also you shouldn't need SauceConnect to run these tests... Can you try without it?

**Comment by rnemeth1980** [comment]
I set Sauce Labs Credentials as environmental variables as described here https://github.com/saucelabs-sample-test-frameworks/Groovy-Geb-Spock-Gradle-Selenium. Now I did set webdriver.gecko.driver and  webdriver.chrome.driver system properties.

I assume these old versions defined in the code cannot handle the latest browsers:

```
ext {
    groovyVersion = '2.4.7'
    gebVersion = '0.13.1'
    seleniumVersion = '2.53.1'
    ciSauceVersion = '1.116'
    sauceJavaCommonVersion = '2.1.21'
    sauceJunitVersion = '2.1.21'
    saucerestVersion = '1.0.33'
    sauceOndemandDriverVersion = '1.2'
    seleniumClientFactoryVersion = '1.2'
    seleniumRemoteDriver = '2.53.1'
    junitVersion = '4.12'
    slf4jVersion = '1.7.13'
}
```

So I set seleniumVersion to 3.0.1.

I tried chrome and firefox tests too, but received exceptions:

**gradlew chromeTest**
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:chromeTest

functionaltest.specs.BingSpec > Search "hello!" FAILED
    java.lang.IllegalStateException
    geb.driver.DriverCreationException
        Caused by: geb.driver.DriverCreationException

functionaltest.specs.BingSpec > Search blank FAILED
    java.lang.IllegalStateException
    geb.driver.DriverCreationException
        Caused by: geb.driver.DriverCreationException

Any idea what could be wrong here?

**Comment by johnroach** [comment]
@rnemeth1980 sorry for late reply, 
I tried the same code on Windows10 PC had no issues.

Have you been able to resolve issue? If not could you please run the same command by adding:

```
--debug --debug
```

Thank you!

**Comment by rnemeth1980** [comment]
@JohnRoach 
hi John,
no problem. I succeded running the framework,  thank you very much.

may I have a general understanding question? 
as my sauce trial expired, I am experimenting with selenium grid instead, by running a hub
on a windows host and running a node on a debian guest system.
the grid is up running. the hub is waiting for tests.
is it possible to send a test to all nodes in the grid, if I would have windows nodes with ie,
and osx nodes with safari?
if yes, how? for which keywords should I look for? can you please suggest any good tutorials to follow?
or sample projects?

thank you very much,
roland

**Comment by johnroach** [comment]
Hi Roland,

Don't know the answer to your question. You could always use SauceLabs ;)

Closing ticket.
